Ext.define('JxkpApp.model.List', {
	extend: 'Ext.data.Model', 
	
	fields: [
		{name: 'TJNY', type: 'string'},
		{name: 'YGGH', type: 'string'},
		{name: 'EMP_NAME', type: 'string'},
		{name: 'GNBKSR', type: 'float'},
		{name: 'GNBKSRTC', type: 'float'},
		{name: 'GNJKSR', type: 'float'},
		{name: 'GNJKSRTC', type: 'float'},
		{name: 'GJSR', type: 'float'},
		{name: 'GJSRTC', type: 'float'},
		{name: 'GJEYBSR', type: 'float'},
		{name: 'GJEYBSRTC', type: 'float'},
		{name: 'GNBKJS', type: 'float'},
		{name: 'GNJKJS', type: 'float'},
		{name: 'GJJS', type: 'float'},
		{name: 'GJEYBJS', type: 'float'},
		{name: 'LSJXHJ', type: 'float'},
		{name: 'TTJS', type: 'float'},
		{name: 'TT2JS', type: 'float'},
		{name: 'TGXHYJ', type: 'float'},
		{name: 'TDSHKJS', type: 'float'},
		{name: 'TLGJS', type: 'float'},
		{name: 'TDJXHJ', type: 'float'},
		{name: 'JXHJ', type: 'float'},
		{name: 'SRTCHJ', type: 'float'},
		{name: 'JSTTJS', type: 'float'},
		{name: 'ZLXYBT', type: 'float'},
		{name: 'FDJBGZ', type: 'float'},
		{name: 'LTBKH', type: 'float'},
		{name: 'SCBKH', type: 'float'},
		{name: 'RJBKH', type: 'float'},
		{name: 'YKBKH', type: 'float'},
		{name: 'JCBKH', type: 'float'},
		{name: 'FBBKH', type: 'float'},
		{name: 'WYBKH', type: 'float'},
		{name: 'DZKHJS', type: 'float'},
		{name: 'YFHJ', type: 'float'}
	]
});